### ISSUE TITLE
Integrate setup scripts with the LSP SDK project

### ISSUE THREAD

**Issue by kieferrm** [kieferrm/lsp-dev-setup#1]
@dbaeumer  it seems others can benefit from the setup I used as well. We should think about generalizing these scripts and link to them from https://github.com/Microsoft/vscode-languageserver-node.

**Comment by dbaeumer** [comment]
@kieferrm makes sense. Should we add them to the corresponding LSP repository then.

**Comment by kieferrm** [comment]
That would make sense to me. I'll take a stab at it.

**Comment by dbaeumer** [comment]
@kieferrm I added a script a while ago to the Microsoft/vscode-languageserver-node that sets up the sym links. It is: `npm run symlink`. I think you can close this one.
